# Generated by Django 6.0.5 on 2026-05-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuarioId', models.UUIDField(primary_key=True, serialize=False)),
                ('delegacaoId', models.UUIDField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('perfil', models.CharField(choices=[('OPERADOR', 'Operador'), ('GESTOR', 'Gestor'), ('FINANCEIRO', 'Financeiro'), ('DIRECAO', 'Direção'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credenciais',
            },
        ),
    ]
