# Generated by Django 6.0.5 on 2026-05-23 01:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('atualizadoEm', models.DateTimeField(auto_now=True)),
                ('usuarioId', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clienteId', models.UUIDField()),
                ('ordemServicoId', models.UUIDField(null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALDO_FINAL', 'Saldo Final'), ('MENSALIDADE', 'Mensalidade')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Parcial'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida')], max_length=20)),
                ('dataVencimento', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuarioId', models.UUIDField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('referenciaBancaria', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('contaReceberId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.contareceber')),
            ],
        ),
    ]
