# Generated by Django 6.0.5 on 2026-05-25 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatarioId', models.UUIDField(null=True)),
                ('tipoDestinatario', models.CharField(choices=[('USUARIO', 'Utilizador do sistema'), ('CLIENTE', 'Cliente externo'), ('SISTEMA', 'Notificacao de sistema - sem destinatario especifico')], max_length=20)),
                ('canal', models.CharField(choices=[('INTERNO', 'Registro interno - consultavel no frontend'), ('EMAIL', 'Envio de email via SMTP')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('evento', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('enviado', models.BooleanField(default=False)),
                ('lida', models.BooleanField(default=False)),
                ('erro', models.TextField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
