# Generated by Django 6.0.4 on 2026-05-14 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('morada', models.CharField(blank=True, max_length=500, null=True)),
                ('flagAssociado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Delegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegacao_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDelegacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delegacaoId', models.UUIDField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes', to='clientes.cliente')),
            ],
            options={
                'db_table': 'cliente_delegacoes',
                'unique_together': {('clienteId', 'delegacaoId')},
            },
        ),
    ]
