# Generated by Django 6.0.4 on 2026-05-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegacao',
        ),
        migrations.AlterModelOptions(
            name='clientedelegacao',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientedelegacao',
            name='clienteId',
            field=models.ForeignKey(db_column='clienteId', on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes', to='clientes.cliente'),
        ),
    ]
