version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/auth_service:/app
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings
