# Generated by Django 6.0.4 on 2026-04-28 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('passwordHash', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('O', 'Operador de delegacao'), ('G', 'Gestor de delegacao'), ('F', 'Financeiro'), ('D', 'Direcao'), ('A', 'Administrador do sistema')], default='O', max_length=1)),
                ('delegacaoId', models.IntegerField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2026, 4, 28, 14, 52, 22, 389877))),
            ],
        ),
    ]
