# Generated by Django 6.0.4 on 2026-04-28 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 14, 53, 50, 94233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='delegacaoId',
            field=models.IntegerField(),
        ),
    ]
