# Generated by Django 6.0.4 on 2026-04-28 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_createdat_alter_usuario_delegacaoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 28, 14, 54, 39, 226897, tzinfo=datetime.timezone.utc)),
        ),
    ]
